-- H2 2.4.240; 
SET DB_CLOSE_DELAY -1;         
;              
CREATE USER IF NOT EXISTS "SA" SALT '49f86c3b98c15e70' HASH '742cf391ea4f4ca98fc7fd249f16e5e62cff67f1d890443b2d54075fa089fdba' ADMIN;          
CREATE MEMORY TABLE "PUBLIC"."GAMES"(
    "ACHIEVEMENTS_TOTAL" INTEGER,
    "ACHIEVEMENTS_UNLOCKED" INTEGER,
    "COMFORT_GAME" BOOLEAN NOT NULL,
    "COMPLETION_PERCENT" INTEGER,
    "FINISHED_DATE" DATE,
    "GAMEPLAY_SCORE" INTEGER,
    "GOTY_CONTENDER" BOOLEAN NOT NULL,
    "HOURS_PLAYED" INTEGER,
    "PLATINUM_TROPHY" BOOLEAN NOT NULL,
    "PRICE_PAID_EUR" NUMERIC(8, 2),
    "PURCHASE_DATE" DATE,
    "RATING" INTEGER,
    "RECOMMEND_TO_FRIEND" BOOLEAN NOT NULL,
    "RELEASE_YEAR" INTEGER,
    "REPLAY_VALUE" INTEGER,
    "SOUNDTRACK_SCORE" INTEGER,
    "STARTED_DATE" DATE,
    "STORY_SCORE" INTEGER,
    "VISUALS_SCORE" INTEGER,
    "ADDED_BY_ID" BIGINT,
    "CREATED_AT" TIMESTAMP(6),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 11) NOT NULL,
    "UPDATED_AT" TIMESTAMP(6),
    "CURRENT_BUILD" CHARACTER VARYING(100),
    "DEVELOPER" CHARACTER VARYING(100),
    "MAIN_PROTAGONIST" CHARACTER VARYING(100),
    "PUBLISHER" CHARACTER VARYING(100),
    "MOOD_TAGS" CHARACTER VARYING(200),
    "TITLE" CHARACTER VARYING(200) NOT NULL,
    "FAVORITE_MOMENT" CHARACTER VARYING(500),
    "PERSONAL_NOTES" CHARACTER VARYING(2000),
    "REVIEW" CHARACTER VARYING(2000),
    "DIFFICULTY" ENUM('EASY', 'HARD', 'NIGHTMARE', 'NORMAL', 'SOULSBORNE', 'STORY'),
    "GENRE" ENUM('ACTION_RPG', 'BATTLE_ROYALE', 'FIGHTING', 'FPS', 'GRAND_STRATEGY', 'INDIE', 'METROIDVANIA', 'MMORPG', 'MOBA', 'OPEN_WORLD', 'PLATFORMER', 'PUZZLE', 'RACING', 'ROGUELIKE', 'RPG', 'SHOOTER', 'SIMULATION', 'SOULSLIKE', 'SPORTS', 'STRATEGY', 'SURVIVAL', 'SURVIVAL_HORROR', 'VISUAL_NOVEL') NOT NULL,
    "PLATFORM" ENUM('BROWSER', 'MOBILE_ANDROID', 'MOBILE_IOS', 'PC_EPIC', 'PC_GAMEPASS', 'PC_GOG', 'PC_STEAM', 'PS4', 'PS5', 'RETRO_HANDHELD', 'STEAM_DECK', 'SWITCH', 'VR_PSVR', 'VR_QUEST', 'XBOX_ONE', 'XBOX_SERIES') NOT NULL,
    "PLAY_STYLE" ENUM('COMPLETIONIST', 'CO_OP_COUCH', 'CO_OP_ONLINE', 'MMO_GUILD', 'PVP_CASUAL', 'PVP_COMPETITIVE', 'SOLO', 'SPEEDRUN'),
    "SECONDARY_GENRE" ENUM('ACTION_RPG', 'BATTLE_ROYALE', 'FIGHTING', 'FPS', 'GRAND_STRATEGY', 'INDIE', 'METROIDVANIA', 'MMORPG', 'MOBA', 'OPEN_WORLD', 'PLATFORMER', 'PUZZLE', 'RACING', 'ROGUELIKE', 'RPG', 'SHOOTER', 'SIMULATION', 'SOULSLIKE', 'SPORTS', 'STRATEGY', 'SURVIVAL', 'SURVIVAL_HORROR', 'VISUAL_NOVEL'),
    "STATUS" ENUM('ABANDONED', 'BACKLOG', 'BEATEN', 'COMPLETED_100', 'ON_HOLD', 'PLAYING', 'REPLAYING', 'WISHLIST') NOT NULL
);         
ALTER TABLE "PUBLIC"."GAMES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4073AA1_4" PRIMARY KEY("ID"); 
-- 10 +/- SELECT COUNT(*) FROM PUBLIC.GAMES;   
INSERT INTO "PUBLIC"."GAMES" VALUES
(42, 42, FALSE, 100, DATE '2024-06-28', 10, TRUE, 142, TRUE, 59.99, DATE '2024-03-14', 5, TRUE, 2022, 9, 10, DATE '2024-03-15', 9, 9, 1, TIMESTAMP '2026-05-27 11:49:24.967373', 1, TIMESTAMP '2026-05-27 11:49:24.967379', 'Faith / Strength dragon-slayer, RL150', 'FromSoftware', 'Tarnished (custom)', 'Bandai Namco', 'Sublime, melancholy, weekly therapy session, dark beauty', 'Elden Ring', 'Beating Malenia on attempt 87 after rage-quitting for 3 weeks. Genuinely shed a tear.', 'Platinum unlocked. Best game of the decade for me. Shadow of the Erdtree DLC waiting in queue.', U&'FromSoft''s magnum opus. The Lands Between is the greatest open world ever designed \2014 every corner rewards exploration. Boss design is unparalleled. Got the Platinum after 142 hours. Already replaying as a wizard.', 'SOULSBORNE', 'SOULSLIKE', 'PS5', 'SOLO', 'OPEN_WORLD', 'COMPLETED_100'),
(54, 28, FALSE, 65, NULL, 10, TRUE, 87, FALSE, 59.99, DATE '2024-08-03', 5, TRUE, 2023, 10, 9, DATE '2024-08-05', 10, 9, 1, TIMESTAMP '2026-05-27 11:49:24.974739', 2, TIMESTAMP '2026-05-27 11:49:24.974745', 'Half-elf paladin, oath of vengeance, charisma 18', 'Larian Studios', 'The Dark Urge (Tav custom)', 'Larian Studios', 'Sprawling, romantic, emergent storytelling, party banter heaven', 'Baldur''s Gate 3', 'Astarion''s full romance arc had me sobbing at 2am on a Tuesday. Larian put EMOTIONS in here.', 'On Act 3, taking it slow. Already planning the evil playthrough. GOTY 2023 hands down.', 'The high water mark for CRPGs. Every decision matters, every NPC has depth, the dice rolls are tense in the best way. Halsin enjoyers stay winning.', 'NORMAL', 'RPG', 'PC_STEAM', 'SOLO', 'ACTION_RPG', 'PLAYING'),
(NULL, NULL, TRUE, 70, NULL, 10, TRUE, 54, FALSE, 29.99, DATE '2024-05-06', 5, TRUE, 2024, 10, 10, DATE '2024-05-06', 9, 10, 1, TIMESTAMP '2026-05-27 11:49:24.975953', 3, TIMESTAMP '2026-05-27 11:49:24.975959', U&'Melino\00eb / Sister Blade + Witch''s Staff', 'Supergiant Games', U&'Melino\00eb', 'Supergiant Games', 'Mythological, addictive, run-based comfort, peak Supergiant', 'Hades II', 'Every interaction with Aphrodite. The voice direction is insane.', 'Comfort game. One run before bed every night. Cannot wait for full release.', 'Supergiant somehow improved on Hades. The witch''s staff and combat magic system feels FRESH. The art direction makes me want to cry. Still in early access and already a 10/10.', 'HARD', 'ROGUELIKE', 'PC_STEAM', 'SOLO', 'ACTION_RPG', 'PLAYING'),
(NULL, NULL, FALSE, 40, NULL, 10, TRUE, 32, FALSE, 19.99, DATE '2025-09-04', 5, TRUE, 2025, 9, 10, DATE '2025-09-04', 9, 10, 1, TIMESTAMP '2026-05-27 11:49:24.977066', 4, TIMESTAMP '2026-05-27 11:49:24.977094', 'Hornet, default needle, Silk Soar', 'Team Cherry', 'Hornet', 'Team Cherry', 'Wait was worth it, vast, melancholy bug kingdom, art-as-religion', 'Hollow Knight: Silksong', 'The Citadel music drop. Goosebumps. Christopher Larkin remains undefeated.', 'Still early game. Taking it slow because I don''t want it to end.', '7 years late but every minute is worth it. Hornet''s moveset feels distinct from the Knight. Pharloom''s biomes are stunning. Team Cherry cooked.', 'HARD', 'METROIDVANIA', 'SWITCH', 'SOLO', 'PLATFORMER', 'PLAYING'),
(49, 49, TRUE, 100, DATE '2021-03-18', 9, FALSE, 287, FALSE, 13.99, DATE '2020-11-02', 5, TRUE, 2016, 10, 10, DATE '2020-11-05', 8, 7, 1, TIMESTAMP '2026-05-27 11:49:24.97883', 5, TIMESTAMP '2026-05-27 11:49:24.97884', 'Year 6, married Sebastian, full Community Center', 'ConcernedApe', 'The Farmer (custom)', 'ConcernedApe', 'Cozy, healing, my comfort game, soundtrack therapy', 'Stardew Valley', 'Reaching the bottom of Skull Cavern for the first time. Pure adrenaline.', 'Will keep replaying forever. Update 1.6 brought me back. Forever indebted to Eric Barone.', 'ConcernedApe alone made what Stardew is. The fact that one human created this is staggering. My most-played game ever. 287 hours and counting through replays.', 'STORY', 'SIMULATION', 'PC_STEAM', 'SOLO', 'INDIE', 'COMPLETED_100'),
(54, 38, FALSE, 100, DATE '2024-05-10', 9, TRUE, 96, FALSE, 69.99, DATE '2024-02-29', 5, TRUE, 2024, 7, 10, DATE '2024-03-01', 10, 10, 1, TIMESTAMP '2026-05-27 11:49:24.980071', 6, TIMESTAMP '2026-05-27 11:49:24.980076', 'Cloud + Tifa + Aerith team, Materia maxed', 'Square Enix', 'Cloud Strife', 'Square Enix', 'Sprawling, emotional, nostalgia-charged, ambitious', 'Final Fantasy VII Rebirth', 'Aerith''s chapter. They knew exactly what they were doing. Sobbed.', U&'Going for Platinum eventually. Not 100% yet \2014 saving combat sim grind for off-season.', 'The middle of the remake trilogy nails what FFVII fans needed. Open zones feel alive, combat is electric, music elevates everything. Mini-games are a love letter to PS1 era.', 'NORMAL', 'RPG', 'PS5', 'SOLO', 'ACTION_RPG', 'BEATEN');
INSERT INTO "PUBLIC"."GAMES" VALUES
(57, 44, FALSE, 95, DATE '2024-01-06', 8, FALSE, 108, FALSE, 29.99, DATE '2023-10-10', 4, TRUE, 2020, 7, 9, DATE '2023-10-12', 9, 10, 1, TIMESTAMP '2026-05-27 11:49:24.981043', 7, TIMESTAMP '2026-05-27 11:49:24.981048', 'Netrunner V, full quickhack monster', 'CD Projekt Red', 'V (Female V)', 'CD Projekt', 'Redemption arc real, neon-soaked, Phantom Liberty completed', 'Cyberpunk 2077', 'Phantom Liberty''s Songbird arc ending. Idris Elba elevated everything.', 'Wait until 2.0+ to play. The 2020 launch version is dead. The current version is a masterpiece.', U&'Played AFTER 2.0 + Phantom Liberty. CDPR fixed it. Night City breathes. The Phantom Liberty expansion is genuinely one of the best RPG DLCs ever \2014 Reed/Songbird dilemma destroyed me.', 'HARD', 'RPG', 'PC_STEAM', 'SOLO', 'OPEN_WORLD', 'BEATEN'),
(78, 78, TRUE, 100, DATE '2023-04-22', 9, TRUE, 218, TRUE, 9.99, DATE '2022-06-14', 5, TRUE, 2015, 8, 10, DATE '2022-07-01', 10, 9, 1, TIMESTAMP '2026-05-27 11:49:24.982151', 8, TIMESTAMP '2026-05-27 11:49:24.982156', 'Igni-focused Geralt, NG+ run completed', 'CD Projekt Red', 'Geralt of Rivia', 'CD Projekt', 'Forever and always, dark fantasy peak, fairytale brutality', 'The Witcher 3: Wild Hunt', 'Bloody Baron''s storyline. No fantasy game has come close to this writing.', 'Got Platinum on PC after console replay. Will return again. Comfort game tier.', 'STILL the gold standard for open-world RPGs. The Bloody Baron quest line alone justifies the entire genre. Blood & Wine DLC is bigger and better than most full games.', 'HARD', 'RPG', 'PC_STEAM', 'SOLO', 'OPEN_WORLD', 'COMPLETED_100'),
(NULL, NULL, FALSE, 55, NULL, 9, FALSE, 73, FALSE, 69.99, DATE '2023-05-12', 4, TRUE, 2023, 7, 10, DATE '2023-05-12', 8, 8, 1, TIMESTAMP '2026-05-27 11:49:24.983131', 9, TIMESTAMP '2026-05-27 11:49:24.983137', 'Master Sword + duped weapons (pre-patch glitch)', 'Nintendo EPD', 'Link', 'Nintendo', 'Magical, exhausting, BotW fatigue, ambition overload', 'Tears of the Kingdom', 'Building the first hover bike with Ultrahand. Genuinely felt like a wizard.', 'On hold since November. Need a long break before tackling the Depths and shrines.', 'Nintendo''s engineering is supernatural but I hit BotW fatigue hard. Ultrahand is genius but combat still has shallow enemy variety. Will return when I have brain space.', 'NORMAL', 'OPEN_WORLD', 'SWITCH', 'SOLO', 'ACTION_RPG', 'ON_HOLD'),
(NULL, NULL, FALSE, 0, NULL, NULL, FALSE, 0, FALSE, 19.99, DATE '2024-10-31', NULL, FALSE, 2019, NULL, NULL, NULL, NULL, NULL, 1, TIMESTAMP '2026-05-27 11:49:24.983948', 10, TIMESTAMP '2026-05-27 11:49:24.983953', NULL, 'Atlus', 'Joker (Ren Amamiya)', 'Sega', NULL, 'Persona 5 Royal', NULL, 'Got it in the Halloween sale. 110+ hours intimidates me. Saving for winter break.', NULL, NULL, 'RPG', 'PC_STEAM', NULL, 'VISUAL_NOVEL', 'BACKLOG');         
CREATE MEMORY TABLE "PUBLIC"."REFRESH_TOKENS"(
    "REVOKED" BOOLEAN NOT NULL,
    "EXPIRY_DATE" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 2) NOT NULL,
    "USER_ID" BIGINT NOT NULL,
    "TOKEN" CHARACTER VARYING(512) NOT NULL
);   
ALTER TABLE "PUBLIC"."REFRESH_TOKENS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C4C" PRIMARY KEY("ID");              
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.REFRESH_TOKENS;           
INSERT INTO "PUBLIC"."REFRESH_TOKENS" VALUES
(FALSE, TIMESTAMP WITH TIME ZONE '2026-06-03 09:54:20.530272+00', 1, 1, '27024e87-5b4c-4d8f-90b4-ede33841f0d9');  
CREATE MEMORY TABLE "PUBLIC"."USERS"(
    "ENABLED" BOOLEAN NOT NULL,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 3) NOT NULL,
    "REGISTERED_AT" TIMESTAMP(6) NOT NULL,
    "USERNAME" CHARACTER VARYING(50) NOT NULL,
    "EMAIL" CHARACTER VARYING(100) NOT NULL,
    "PASSWORD" CHARACTER VARYING(255) NOT NULL,
    "ROLE" ENUM('ADMIN', 'USER') NOT NULL
);              
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D49" PRIMARY KEY("ID");      
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.USERS;    
INSERT INTO "PUBLIC"."USERS" VALUES
(TRUE, 1, TIMESTAMP '2026-05-27 11:49:24.87941', 'admin', 'admin@gamelog.hr', '$2a$10$Fh82Hp5ulu2zgUcn6xYzPuX3R7dDLuNssnRBchADOdGJQJJndyrBC', 'ADMIN'),
(TRUE, 2, TIMESTAMP '2026-05-27 11:49:24.96614', 'user', 'user@gamelog.hr', '$2a$10$SCVn2syqWKhsQMkaT/6CTu1TEyXQnoiLYe6j.dAShWi3Ht97rt/vu', 'USER');               
ALTER TABLE "PUBLIC"."GAMES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4073" CHECK(("GAMEPLAY_SCORE" >= 1)
    AND ("GAMEPLAY_SCORE" <= 10)) NOCHECK;
ALTER TABLE "PUBLIC"."GAMES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_407" CHECK(("COMPLETION_PERCENT" <= 100)
    AND ("COMPLETION_PERCENT" >= 0)) NOCHECK;        
ALTER TABLE "PUBLIC"."GAMES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4073AA1_2" CHECK(("STORY_SCORE" >= 1)
    AND ("STORY_SCORE" <= 10)) NOCHECK; 
ALTER TABLE "PUBLIC"."GAMES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4073AA1_3" CHECK(("VISUALS_SCORE" >= 1)
    AND ("VISUALS_SCORE" <= 10)) NOCHECK;             
ALTER TABLE "PUBLIC"."GAMES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" CHECK(("ACHIEVEMENTS_TOTAL" <= 500)
    AND ("ACHIEVEMENTS_TOTAL" >= 0)) NOCHECK;          
ALTER TABLE "PUBLIC"."GAMES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4073AA1_0" CHECK(("REPLAY_VALUE" >= 1)
    AND ("REPLAY_VALUE" <= 10)) NOCHECK;               
ALTER TABLE "PUBLIC"."GAMES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4073AA1_1" CHECK(("SOUNDTRACK_SCORE" >= 1)
    AND ("SOUNDTRACK_SCORE" <= 10)) NOCHECK;       
ALTER TABLE "PUBLIC"."GAMES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4073AA" CHECK(("RATING" <= 5)
    AND ("RATING" >= 1)) NOCHECK;               
ALTER TABLE "PUBLIC"."GAMES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_40" CHECK(("ACHIEVEMENTS_UNLOCKED" <= 500)
    AND ("ACHIEVEMENTS_UNLOCKED" >= 0)) NOCHECK;   
ALTER TABLE "PUBLIC"."GAMES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4073AA1" CHECK(("RELEASE_YEAR" >= 1980)
    AND ("RELEASE_YEAR" <= 2030)) NOCHECK;            
ALTER TABLE "PUBLIC"."GAMES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4073A" CHECK(("HOURS_PLAYED" >= 0)
    AND ("HOURS_PLAYED" <= 10000)) NOCHECK;
ALTER TABLE "PUBLIC"."REFRESH_TOKENS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" UNIQUE NULLS DISTINCT ("USER_ID");
ALTER TABLE "PUBLIC"."REFRESH_TOKENS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C4" UNIQUE NULLS DISTINCT ("TOKEN"); 
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D" UNIQUE NULLS DISTINCT ("USERNAME");       
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D4" UNIQUE NULLS DISTINCT ("EMAIL");         
ALTER TABLE "PUBLIC"."REFRESH_TOKENS" ADD CONSTRAINT "PUBLIC"."FK1LIH5Y2NPSF8U5O3VHDB9Y0OS" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."GAMES" ADD CONSTRAINT "PUBLIC"."FK54T376AOTVKGAXMV519E2V9JN" FOREIGN KEY("ADDED_BY_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;       
